name: Playwright Tests
on:
  push:
    branches: [ main ]
jobs:
  chromium_webkit:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright/python:v1.41.2-jammy
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@master
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Test
      run: pytest -n 2 practice_pytest_playwright/test_multi_browsing.py practice_pytest_playwright/test_hakuna_webkit.py --alluredir=allure-results --browser chromium --browser webkit --tracing on

    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-traces
        path: test-results/

    - name: Get Allure history
      uses: actions/checkout@v4
      if: always()
      continue-on-error: true
      with:
        ref: gh-pages
        path: gh-pages


    - name: Allure report action from marketplace
      uses: simple-elf/allure-report-action@master
      if: always()
      with:
        allure_results: allure-results
        gh_pages: gh-pages
        allure_report: allure-report
        allure_history: allure-history
        keep_reports: 40


    - name: Deploy report to Github Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.TOKEN }}
        publish_branch: gh-pages
        publish_dir: allure-history

  chrome:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    needs: chromium_webkit
    container:
      image: mcr.microsoft.com/playwright/python:v1.41.2-jammy
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@master
      with:
        python-version: '3.11'


    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - uses: browser-actions/setup-chrome@v1

    - name: Run Test
      run: pytest -n 2 practice_pytest_playwright/test_multi_browsing.py --alluredir=allure-results --browser-channel chrome

    - name: Get Allure history
      uses: actions/checkout@v4
      if: always()
      continue-on-error: true
      with:
        ref: gh-pages
        path: gh-pages


    - name: Allure report action from marketplace
      uses: simple-elf/allure-report-action@master
      if: always()
      with:
        allure_results: allure-results
        gh_pages: gh-pages
        allure_report: allure-report
        allure_history: allure-history
        keep_reports: 40


    - name: Deploy report to Github Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.TOKEN }}
        publish_branch: gh-pages
        publish_dir: allure-history

#
#  msedge:
#    timeout-minutes: 60
#    runs-on: ubuntu-latest
#    needs: chrome
#    steps:
#    - uses: actions/checkout@v4
#    - name: Set up Python
#      uses: actions/setup-python@master
#      with:
#        python-version: '3.11'
#
#
#    - name: Install dependencies
#      run: |
#        python -m pip install --upgrade pip
#        pip install -r requirements.txt
#
#    - uses: browser-actions/setup-edge@v1
#
#    - name: Run Test
#      run: pytest -n 2 practice_pytest_playwright/test_multi_browsing.py --alluredir=allure-results --browser-channel msedge
#
#    - name: Get Allure history
#      uses: actions/checkout@v3
#      if: always()
#      continue-on-error: true
#      with:
#        ref: gh-pages
#        path: gh-pages
#
#
#    - name: Allure report action from marketplace
#      uses: simple-elf/allure-report-action@master
#      if: always()
#      with:
#        allure_results: allure-results
#        gh_pages: gh-pages
#        allure_report: allure-report
#        allure_history: allure-history
#        keep_reports: 40
#
#
#    - name: Deploy report to Github Pages
#      if: always()
#      uses: peaceiris/actions-gh-pages@v3
#      with:
#        github_token: ${{ secrets.TOKEN }}
#        publish_branch: gh-pages
#        publish_dir: allure-history
